services:
  qdrant_node1:
    image: qdrant/qdrant:latest
    container_name: qdrant_node1
    environment:
      QDRANT__CLUSTER__ENABLED: true
    volumes:
      - ./data/node1:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    command: "./qdrant --uri http://qdrant_node1:6335"
    restart: unless-stopped
    networks:
      - net

  qdrant_node2:
    image: qdrant/qdrant:latest
    container_name: qdrant_node2
    environment:
      QDRANT__CLUSTER__ENABLED: true
    volumes:
      - ./data/node2:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node2:6335"
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - qdrant_node1

  qdrant_node3:
    image: qdrant/qdrant:latest
    container_name: qdrant_node3
    environment:
      QDRANT__CLUSTER__ENABLED: true
    volumes:
      - ./data/node3:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node3:6335"
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - qdrant_node1

  qdrant_node4:
    image: qdrant/qdrant:latest
    container_name: qdrant_node4
    environment:
      QDRANT__CLUSTER__ENABLED: true
    volumes:
      - ./data/node4:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node4:6335"
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - qdrant_node1

  nginx:
    image: nginx:latest
    container_name: nginx_qdrant
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9090:9090"
      - "9091:9091"
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - qdrant_node1
      - qdrant_node2
      - qdrant_node3
      - qdrant_node4

networks:
    net:
      driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: DEBUG
      cluster:
        enabled: true
        p2p:
          port: 6335
        enable_tls: false
        consensus:
          tick_period_ms: 100
      service:
        host: 0.0.0.0
        http_port: 6333
        grpc_port: 6334